### ISSUE TITLE
Config not being generated

### ISSUE THREAD

**Issue by Kingrc16** [Eufranio/PixelBuilt-Quests#10]
[19:23:33] [Server thread/ERROR] [pixelbuilt-quests]: Could not create the default config! Report it in the plugin issue tracker, and include this stacktrace: 
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: java.util.NoSuchElementException: No value present
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at java.util.Optional.get(Unknown Source)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at online.pixelbuilt.pbquests.utils.Config.load(Config.java:54)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at online.pixelbuilt.pbquests.PixelBuiltQuests.onReload(PixelBuiltQuests.java:78)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.common.event.listener.GameReloadEventListener_PixelBuiltQuests_onReload33.handle(Unknown Source)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:246)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$8(SpongeCommandFactory.java:600)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1156)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:305)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3965)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[19:23:33] [Server thread/INFO] [STDERR]: [online.pixelbuilt.pbquests.utils.Config:load:57]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Lypaka-Dev** [comment]
Interesting. Not even my tweaked version of our little plugin breaks that hard. What environment are you running it in? As in, Sponge version? PBQ version? I don't check here very often, but if you PM me on Discord, I can help out how I can.
@Lypaka#7766

Sincerely, Ryan - coder of PixelBuilt

**Comment by Kingrc16** [comment]
Version 1.2 For PBQ witch is the lasted version according to here  https://github.com/Eufranio/PixelBuilt-Quests/releases & Sponge Forge Version is 1.12.2-7.1.6-snapshot SpongeApi is 7.1.0

**Comment by Lypaka-Dev** [comment]
He has 2.0.jar in the pbquest channel of the Discord.

**Comment by Kingrc16** [comment]
Didn't know there was a discord

**Comment by Kingrc16** [comment]
I also can't find a link to the discord

**Comment by Lypaka-Dev** [comment]
https://discord.gg/JPH5Vr

**Comment by Lypaka-Dev** [comment]
That's how I've been getting here, through the Discord, which I check more often than my GitHub.

**Comment by Kingrc16** [comment]
Thanks for the help I'll try out the newer version

**Comment by Eufranio** [comment]
Irrelevant for the new version, please update!
