### ISSUE TITLE
Console Failing to Execute pbq run command

### ISSUE THREAD

**Issue by Adidasu** [Eufranio/PixelBuilt-Quests#19]
So I'm trying to setup a virtualchest menu where you click on an item in the gui and console runs the command /pbq run default 1 %player_name%. I can do it ingame, but when I type it in console the same error shows up as when I click it in the gui. Here is the error. I am using the recommended version of sponge forge atm (7.2.3) and I'm kind of new to running a server.

16.08 04:56:16 [Server] Server thread/INFO [nucleus]: Server ran the command: /virtualchest open onetimequests Adidasu
16.08 04:56:17 [Server] Server thread/INFO [nucleus]: Server ran the command: /pbq run default 1 Adidasu
16.08 04:56:17 [Server] Server thread/INFO Error occurred while executing command: net.minecraft.server.dedicated.DedicatedServer cannot be cast to org.spongepowered.api.entity.living.player.Player
16.08 04:56:17 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'pbq run default 1 Adidasu' for source DedicatedServer: net.minecraft.server.dedicated.DedicatedServer cannot be cast to org.spongepowered.api.entity.living.player.Player
16.08 04:56:17 [Server] INFO java.lang.ClassCastException: net.minecraft.server.dedicated.DedicatedServer cannot be cast to org.spongepowered.api.entity.living.player.Player
16.08 04:56:17 [Server] INFO at online.pixelbuilt.pbquests.commands.Run.execute(Run.java:17) ~[Run.class:?]
16.08 04:56:17 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.2.3]
16.08 04:56:17 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.2.3]
16.08 04:56:17 [Server] INFO at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.2.3]
16.08 04:56:17 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) ~[SpongeCommandManager.class:1.12.2-2838-7.2.3]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions.processConsole(VirtualChestActions.java:349) ~[VirtualChestActions.class:?]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions$Callback.lambda$accept$2(VirtualChestActions.java:402) ~[VirtualChestActions$Callback.class:?]
16.08 04:56:17 [Server] INFO at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions$Callback.accept(VirtualChestActions.java:402) ~[VirtualChestActions$Callback.class:?]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions$Callback.accept(VirtualChestActions.java:352) ~[VirtualChestActions$Callback.class:?]
16.08 04:56:17 [Server] INFO at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions$Callback.accept(VirtualChestActions.java:404) ~[VirtualChestActions$Callback.class:?]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions$Callback.start(VirtualChestActions.java:373) ~[VirtualChestActions$Callback.class:?]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions$Callback.access$300(VirtualChestActions.java:352) ~[VirtualChestActions$Callback.class:?]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions.submitCommands(VirtualChestActions.java:124) ~[VirtualChestActions.class:?]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.action.VirtualChestActionDispatcher.runCommand(VirtualChestActionDispatcher.java:132) ~[VirtualChestActionDispatcher.class:?]
16.08 04:56:17 [Server] INFO at com.github.ustc_zzzz.virtualchest.inventory.VirtualChestInventory$EventListener.lambda$runCommand$6(VirtualChestInventory.java:418) ~[VirtualChestInventory$EventListener.class:?]
16.08 04:56:17 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_262]
16.08 04:56:17 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_262]

**Comment by Adidasu** [comment]
This is solved, I just needed to run the command without console by getting rid of the "console:" argument.
