### ISSUE TITLE
Magibridge wont work if mcclans is installed.

### ISSUE THREAD

**Issue by Skite69ers** [Eufranio/PixelBuilt-Quests#29]
Here's the logs

`[18.05 16:06:59] [Server] [pool-3-thread-2/ERROR] [magibridge]: Error loading MagiBridge: 
[18.05 16:06:59] [Server] java.lang.NoClassDefFoundErrorio/github/nucleuspowered/nucleus/api/events/NucleusTextTemplateEvent$Broadcast
[18.05 16:06:59] [Server] 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at org.spongepowered.common.event.SpongeEventManager.registerListener(SpongeEventManager.java:248) ~[SpongeEventManager.class:1.12.2-2838-7.3.1-RC4082]
[18.05 16:06:59] [Server] 	at org.spongepowered.common.event.SpongeEventManager.registerListeners(SpongeEventManager.java:315) ~[SpongeEventManager.class:1.12.2-2838-7.3.1-RC4082]
[18.05 16:06:59] [Server] 	at com.magitechserver.magibridge.common.NucleusBridge.init(NucleusBridge.java:33) ~[NucleusBridge.class:?]
[18.05 16:06:59] [Server] 	at com.magitechserver.magibridge.bridge.nucleus.NucleusBridgeImpl.init(NucleusBridgeImpl.java:24) ~[NucleusBridgeImpl.class:?]
[18.05 16:06:59] [Server] 	at com.magitechserver.magibridge.MagiBridge.registerListeners(MagiBridge.java:290) ~[MagiBridge.class:?]
[18.05 16:06:59] [Server] 	at com.magitechserver.magibridge.MagiBridge.lambda$init$13(MagiBridge.java:226) ~[MagiBridge.class:?]
[18.05 16:06:59] [Server] 	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1646) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.3.1-RC4082]
[18.05 16:06:59] [Server] 	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.3.1-RC4082]
[18.05 16:06:59] [Server] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
[18.05 16:06:59] [Server] Caused byjava.lang.ClassNotFoundException: io.github.nucleuspowered.nucleus.api.events.NucleusTextTemplateEvent$Broadcast
[18.05 16:06:59] [Server] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
[18.05 16:06:59] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271]
[18.05 16:06:59] [Server] 	... more
[18.05 16:06:59] [Server] Caused byjava.lang.NullPointerException`

**Comment by Eufranio** [comment]
This is not MagiBridge's repository.
